### ISSUE TITLE
Add no-unnamed-types

### ISSUE THREAD

**Issue by gabro** [buildo/eslint-plugin-tcomb#2]
All tcomb combinators accept a name. For most of them the name is optional.

This rule enforces the presence of a name when declaring a new type.

This rule should allow deciding which combinators should have a name enforced and provide some sensible defaults. E.g. the `t.struct` combinator should always have a name by default, but the `t.list` combinator probably shouldn't.

**Comment by gcanti** [comment]
My preference would be:

(irreducibles are already enforced by tcomb)

Not enforced
- maybe
- list
- union
- intersection
- func

Enforced
- struct
- refinement
- interface
- tuple
- enums
- dict

**Comment by gabro** [comment]
you're talking about defaults, right? My idea is to make it enforceable for every combinator and then ship reasonable defaults

For the defaults I agree with all of them. My only doubt (no strong opinions about it) is the `tuple` combinator.

**Comment by gcanti** [comment]
> you're talking about defaults, right?

yep
